DEBUG 2018-02-06 04:26:14,943: 	 Executing command: 'submit'
DEBUG 2018-02-06 04:26:14,943: 	 Found CRAB cache file /uscms/home/mlu/.crab3
DEBUG 2018-02-06 04:26:14,950: 	 Checking credentials
DEBUG 2018-02-06 04:26:14,950: 	 Found proxy file /tmp/x509up_u52213
DEBUG 2018-02-06 04:26:14,951: 	 Getting proxy life time left
DEBUG 2018-02-06 04:26:15,054: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52213 -timeleft
 output : 82185

 error: 
 retcode : 0
DEBUG 2018-02-06 04:26:15,157: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u52213 -actimeleft
 output : 82185

 error: 
 retcode : 0
DEBUG 2018-02-06 04:26:15,158: 	 Proxy valid for 22:49:45 hours
INFO 2018-02-06 04:26:15,159: 	 Will use CRAB configuration file Zcrab/crab3_analysisZA.py
DEBUG 2018-02-06 04:26:15,159: 	 Loading CRAB configuration file.
DEBUG 2018-02-06 04:26:15,162: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2018-02-06 04:26:15,162: 	 Working area '/uscms_data/d3/mlu/CMSSW_8_0_26_patch2/src/VAJets/PKUTreeMaker/test/crab_Z-ZA-1' already exists 
Please change the requestName in the config file
ERROR 2018-02-06 04:26:15,162: 	 Caught exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 160, in <module>
    client()
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/bin/crab", line 146, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/submit.py", line 34, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/Commands/SubCommand.py", line 302, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/crab3/slc6_amd64_gcc493/cms/crabclient/3.3.1707.patch1/lib/python2.7/site-packages/CRABClient/ClientUtilities.py", line 396, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/uscms_data/d3/mlu/CMSSW_8_0_26_patch2/src/VAJets/PKUTreeMaker/test/crab_Z-ZA-1' already exists 
Please change the requestName in the config file
